name: ml_fastapi_py39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn==1.3.2
  - pytest
  - requests
  - fastapi=0.63.0
  - uvicorn
  - gunicorn
  - joblib
