name: Run Tests and Lint

on:
  push:
    branches:
      - master

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          auto-update-conda: true
          activate-environment: ml_fastapi  # Activate the environment after creation
          environment-file: starter/environment.yml  # Use your existing environment.yml
          use-fastcache: true

      # Step 3: Verify Conda Environment
      - name: Verify Conda Environment
        run: conda info --envs

      # Step 4: Install Additional Dependencies (if needed)
      - name: Install Dependencies
        run: |
          conda activate ml_fastapi
          python -m pip install --upgrade pip
          pip install flake8

      # Step 5: Run Linter (flake8)
      - name: Run Linter (flake8)
        run: |
          conda activate ml_fastapi
          flake8 . --max-line-length=127 --statistics

      # Step 6: Run Tests (pytest)
      - name: Run Tests (pytest)
        run: |
          conda activate ml_fastapi
          pytest -v
