name: Run Tests and Lint

on:
  push:
    branches:
      - master

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8  # Install pytest & flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Linter (flake8)
        run: flake8 .

      - name: Run Tests (pytest)
        run: pytest -v
